# Generated by Django 2.2.3 on 2019-07-09 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('tv_choice', models.CharField(choices=[('KTRK', 'KTRK'), ('RTR', 'RTR'), ('ORT', 'ORT'), ('NBT', 'NBT'), ('APRIL', 'APRIL')], max_length=5)),
                ('dates', models.IntegerField()),
                ('price', models.PositiveIntegerField()),
            ],
        ),
    ]
