# Generated by Django 2.2.3 on 2019-07-09 11:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_tv', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='dates',
            new_name='post_dates',
        ),
        migrations.AddField(
            model_name='post',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='post',
            name='reception',
            field=models.BooleanField(default=False),
        ),
    ]
