# Generated by Django 2.2.3 on 2019-07-09 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_tv', '0002_auto_20190709_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
