# Generated by Django 2.2.2 on 2019-07-10 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_tv', '0005_auto_20190710_1237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='price',
            new_name='total_price',
        ),
    ]
