# Generated by Django 2.2.2 on 2019-07-10 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_tv', '0006_auto_20190710_1354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='total_price',
            new_name='quantity_symbols',
        ),
    ]
