# Generated by Django 2.2.2 on 2019-07-10 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_tv', '0007_auto_20190710_1356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tv_choice',
            new_name='choice',
        ),
    ]
