# Generated by Django 2.2.2 on 2019-07-10 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_tv', '0008_auto_20190710_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='tv_price',
            field=models.FloatField(),
        ),
    ]
