# Generated by Django 2.2.2 on 2019-07-10 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_tv', '0009_auto_20190710_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='total_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
