# Generated by Django 2.2.2 on 2019-07-10 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_tv', '0010_post_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_dates',
            field=models.CharField(max_length=255),
        ),
    ]
