# Generated by Django 2.2.2 on 2019-07-10 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_tv', '0011_auto_20190710_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_dates',
        ),
        migrations.AddField(
            model_name='post',
            name='kwargs**',
            field=models.TextField(default=1, verbose_name='args*'),
            preserve_default=False,
        ),
    ]
