# Generated by Django 2.2.2 on 2019-07-16 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_tv', '0013_auto_20190710_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
