# Generated by Django 2.2.3 on 2019-07-17 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_tv', '0014_post_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_dates',
            field=models.TextField(),
        ),
    ]
