# Generated by Django 2.2.3 on 2019-07-17 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_tv', '0015_auto_20190717_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_dates',
            field=models.DateField(),
        ),
    ]
