# Generated by Django 2.2.3 on 2019-07-18 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_tv', '0018_auto_20190717_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_dates',
            field=models.IntegerField(),
        ),
    ]
