# Generated by Django 2.2.3 on 2019-07-18 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_tv', '0019_auto_20190718_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_dates',
            field=models.TextField(max_length=100),
        ),
    ]
