# Generated by Django 2.2.3 on 2019-07-18 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_tv', '0020_auto_20190718_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_dates',
            field=models.CharField(max_length=1000),
        ),
    ]
