# Generated by Django 2.2.3 on 2019-07-18 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_tv', '0022_auto_20190718_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='choice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='posts', to='site_tv.Choice'),
            preserve_default=False,
        ),
    ]
