# Generated by Django 2.2.3 on 2019-07-18 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_tv', '0023_auto_20190718_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='posts', to='site_tv.Choice'),
        ),
    ]
