# Generated by Django 2.2.3 on 2019-07-18 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_tv', '0024_auto_20190718_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='quantity_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
